name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore poc-net-api/demo-api.csproj

      - name: Build
        run: dotnet build poc-net-api/demo-api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test poc-net-api/demo-api.csproj --no-build --verbosity normal
